import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import type { Server } from "node:http";
import dotenv from "dotenv";
import { createApp } from "../app.js";
import { prisma } from "../db/prisma.js";

dotenv.config();
const emailA = `phase13-a-${Date.now()}@example.com`; const emailB = `phase13-b-${Date.now()}@example.com`; const password = "securepass1";
let server: Server; let base = ""; let cookieA = ""; let cookieB = ""; let userA = ""; let userB = "";
function cookie(response: Response) { const value = response.headers.get("set-cookie") ?? ""; const match = /lifeos\.sid=([^;]+)/.exec(value); return match ? `lifeos.sid=${match[1]}` : ""; }
async function api(path: string, init: RequestInit = {}, session = cookieA) { const headers = new Headers(init.headers); if (session) headers.set("Cookie", session); if (init.body && !(init.body instanceof FormData) && !headers.has("Content-Type")) headers.set("Content-Type", "application/json"); return fetch(`${base}${path}`, { ...init, headers }); }
describe("Phase 13 search and inbox", () => {
 before(async () => { const app = createApp(); await new Promise<void>(resolve => { server = app.listen(0, "127.0.0.1", resolve); }); const address = server.address(); if (!address || typeof address === "string") throw new Error("No test server address"); base = `http://127.0.0.1:${address.port}/api`; const a = await api("/auth/register", { method: "POST", body: JSON.stringify({ email: emailA, password }) }, ""); assert.equal(a.status, 201); cookieA = cookie(a); userA = ((await a.json()) as { user: { id: string } }).user.id; const b = await api("/auth/register", { method: "POST", body: JSON.stringify({ email: emailB, password }) }, ""); assert.equal(b.status, 201); cookieB = cookie(b); userB = ((await b.json()) as { user: { id: string } }).user.id; });
 after(async () => { await prisma.user.deleteMany({ where: { email: { in: [emailA, emailB] } } }); await new Promise<void>((resolve, reject) => server.close(err => err ? reject(err) : resolve())); await prisma.$disconnect(); });
 it("search and inbox require authentication; validates input and returns empty results safely", async () => { assert.equal((await api("/search?q=milk", {}, "")).status, 401); assert.equal((await api("/inbox", {}, "")).status, 401); assert.equal((await api("/inbox", { method: "POST", body: JSON.stringify({ title: "private" }) }, "")).status, 401); assert.equal((await api("/search?q=x")).status, 400); const result = await api("/search?q=unlikely-query-token"); assert.equal(result.status, 200); assert.deepEqual((await result.json() as { results: unknown[] }).results, []); });
 it("searches supported record types and isolates results by owner", async () => { const document = await prisma.document.create({ data: { userId: userA, title: "SearchToken passport", category: "PASSPORT", notes: "travel wallet" } }); await prisma.subscription.create({ data: { userId: userA, name: "SearchToken service", billingInterval: "MONTHLY", provider: "SearchToken provider" } }); const purchase = await prisma.purchase.create({ data: { userId: userA, name: "SearchToken laptop", purchasedOn: new Date("2026-01-01T00:00:00Z"), notes: "SearchToken invoice" } }); await prisma.warranty.create({ data: { userId: userA, purchaseId: purchase.id, endsOn: new Date("2027-01-01T00:00:00Z"), provider: "SearchToken warranty" } }); await prisma.deadline.create({ data: { userId: userA, title: "SearchToken deadline", dueOn: new Date("2027-01-01T00:00:00Z") } }); await prisma.recurringPayment.create({ data: { userId: userA, name: "SearchToken payment", billingInterval: "MONTHLY" } }); await prisma.renewal.create({ data: { userId: userA, title: "SearchToken renewal", dueOn: new Date("2027-01-01T00:00:00Z") } }); await prisma.document.create({ data: { userId: userB, title: "SearchToken foreign", category: "OTHER" } }); const response = await api("/search?q=SearchToken"); assert.equal(response.status, 200); const results = (await response.json() as { results: Array<{ type: string; title: string }> }).results; for (const type of ["document", "subscription", "purchase", "warranty", "deadline", "recurring_payment", "renewal"]) assert.ok(results.some(x => x.type === type), `missing ${type}`); assert.ok(!results.some(x => x.title.includes("foreign"))); assert.ok(results.some(x => x.id === document.id)); const bResponse = await api("/search?q=SearchToken", {}, cookieB); assert.ok(!(await bResponse.json() as { results: Array<{ title: string }> }).results.some(x => x.title.includes("passport"))); });
 it("creates, reads, edits, filters, triages and deletes owned inbox items", async () => { const doc = await prisma.document.create({ data: { userId: userA, title: "Linked inbox document", category: "RECEIPT" } }); const created = await api("/inbox", { method: "POST", body: JSON.stringify({ title: "New inbox receipt", notes: "check warranty", linkedDocumentId: doc.id }) }); assert.equal(created.status, 201); const item = (await created.json() as { item: { id: string; linkedDocument: { id: string } } }).item; assert.equal(item.linkedDocument.id, doc.id); assert.equal((await api(`/inbox/${item.id}`)).status, 200); assert.equal((await api("/inbox?status=UNREVIEWED")).status, 200); const edit = await api(`/inbox/${item.id}`, { method: "PATCH", body: JSON.stringify({ title: "Edited receipt" }) }); assert.equal((await edit.json() as { item: { title: string } }).item.title, "Edited receipt"); const triaged = await api(`/inbox/${item.id}/triage`, { method: "PATCH", body: JSON.stringify({ status: "CATEGORIZED" }) }); assert.equal((await triaged.json() as { item: { status: string } }).item.status, "CATEGORIZED"); assert.equal((await api(`/inbox/${item.id}?x=1`, {}, cookieB)).status, 404); assert.equal((await api(`/inbox/${item.id}/triage`, { method: "PATCH", body: JSON.stringify({ status: "BAD" }) })).status, 400); assert.equal((await api("/inbox", { method: "POST", body: JSON.stringify({ title: "Foreign document", linkedDocumentId: (await prisma.document.create({ data: { userId: userB, title: "Other user's file", category: "OTHER" } })).id }) })).status, 400); assert.equal((await api(`/inbox/${item.id}`, {}, cookieB)).status, 404); assert.equal((await api(`/inbox/${item.id}`, { method: "PATCH", body: JSON.stringify({ notes: "no" }) }, cookieB)).status, 404); assert.equal((await api("/inbox", { method: "POST", body: JSON.stringify({ title: "" }) })).status, 400); const form = new FormData(); form.set("file", new Blob([Buffer.from("%PDF-1.7 inbox test")], { type: "application/pdf" }), "scan.pdf"); const uploaded = await api("/inbox", { method: "POST", body: form }); assert.equal(uploaded.status, 201); const uploadedItem = (await uploaded.json()) as { item: { id: string; originalFileName: string; storageKey?: string } }; assert.equal(uploadedItem.item.originalFileName, "scan.pdf"); assert.equal(uploadedItem.item.storageKey, undefined, "private storage key must not be exposed"); const download = await api(`/inbox/${uploadedItem.item.id}/download`); assert.equal(download.status, 200); assert.equal(await download.text(), "%PDF-1.7 inbox test"); assert.equal((await api(`/inbox/${uploadedItem.item.id}/download`, {}, cookieB)).status, 404); assert.equal((await api(`/inbox/${item.id}`, { method: "DELETE" })).status, 204); assert.equal((await api(`/inbox/${item.id}`)).status, 404); assert.equal((await api(`/inbox/${uploadedItem.item.id}`, { method: "DELETE" })).status, 204); });
});
